services:
  rtt-drone-fds-dev:
    build: .
    volumes:
      - .:/workspace/radio-telemetry-tracker-drone-fds
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/bus/usb/001/006:/dev/bus/usb/001/006"
    privileged: true
    command: /bin/sh -c "while sleep 10000; do :; done"
    group_add:
      - dialout
    environment:
      - PYTHONUNBUFFERED=1
      - RUN_MODE=dev
      - GPS_I2C_BUS=1
      - GPS_ADDRESS=0x42
      - PING_FINDER_CONFIG='{}'
      - WAIT_TIME=60

  rtt-drone-fds-release:
    image: ghcr.io/ucsd-e4e/radio-telemetry-tracker-drone-fds:latest
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/bus/usb/001/006:/dev/bus/usb/001/006"
    privileged: true
    group_add:
      - dialout
    environment:
      - PYTHONUNBUFFERED=1
      - GPS_I2C_BUS=1
      - GPS_ADDRESS=0x42
      - PING_FINDER_CONFIG='{}'
      - WAIT_TIME=60