services:
  rtt-drone-fds-release:
    image: ghcr.io/ucsd-e4e/radio-telemetry-tracker-drone-fds:latest
    volumes:
      - /media/usbstick:/media/usbstick
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/bus/usb/001/006:/dev/bus/usb/001/006"
    privileged: true
    group_add:
      - dialout
    environment:
      - PYTHONUNBUFFERED=1
      - GPS_I2C_BUS=1
      - GPS_ADDRESS=0x42
      - PING_FINDER_CONFIG='{}'
    pull_policy: always