services:
  rtt-drone-fds:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    volumes:
      - /media/usbstick:/media/usbstick
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/bus/usb:/dev/bus/usb"
    privileged: true
    group_add:
      - dialout
    environment:
      - PYTHONUNBUFFERED=1
      - GPS_I2C_BUS=${GPS_I2C_BUS:-1}
      - GPS_ADDRESS=${GPS_ADDRESS:-0x42}
      - PING_FINDER_CONFIG=${PING_FINDER_CONFIG:-'{}'}
      - WAIT_TO_START_TIMER=${WAIT_TO_START_TIMER:-300}
      - RUN_TIMER=${RUN_TIMER:-1800}
