services:
  rtt-drone-fds-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace/radio-telemetry-tracker-drone-fds
      - /media/usbstick:/media/usbstick 
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/bus/usb/001/006:/dev/bus/usb/001/006"
    privileged: true
    command: /bin/sh -c "while sleep 10000; do :; done"
    group_add:
      - dialout
    environment:
      - PYTHONUNBUFFERED=1
      - RUN_MODE=dev
      - GPS_I2C_BUS=1
      - GPS_ADDRESS=0x42
      - PING_FINDER_CONFIG='{}'