[tool.poetry]
name = "radio-telemetry-tracker-drone-fds"
version = "0.1.0"
description = ""
authors = ["Tyler Flar <tflar@ucsd.edu>"]
packages = [
    { include = "radio_telemetry_tracker_drone_fds" },
]

[tool.poetry.dependencies]
python = "^3.12"
smbus2 = "^0.4.3"

[tool.poetry.dev-dependencies]
flake8 = "^7.1.1"
black = "^24.8.0"

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.poetry.scripts]
rttDroneFDS = "radio_telemetry_tracker_drone_fds.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
